# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

sudo: false

notifications:
  email: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

services:
  - mysql
  - postgresql
  - redis
  - rabbitmq

addons:
  postgresql: "9.6"

env:
  global:
    - E2E="no"
  matrix:
    - COOKIECUTTER_DATABASE=postgresql COOKIECUTTER_ELASTICSEARCH=elasticsearch5 ES_VERSION=5.6.4
    - COOKIECUTTER_DATABASE=mysql COOKIECUTTER_ELASTICSEARCH=elasticsearch5 ES_VERSION=5.6.4
    - COOKIECUTTER_DATABASE=postgresql COOKIECUTTER_ELASTICSEARCH=elasticsearch6 ES_VERSION=6.2.2
    - COOKIECUTTER_DATABASE=mysql COOKIECUTTER_ELASTICSEARCH=elasticsearch6 ES_VERSION=6.2.2

python:
  - "3.5"

before_install:
  - mkdir /tmp/elasticsearch
  - "wget -O - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/elasticsearch > /tmp/local-es.log &"
  - "nvm install 6; nvm use 6"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install cookiecutter twine wheel coveralls requirements-builder sphinx"

before_script:
  # Allow ES to start
  - sleep 10
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200 && echo "Elasticsearch is up!" || cat /tmp/local-es.log


script:
  - "./run-tests.sh"
